# Обработка и анализ табличных данных

In [256]:
import pandas as pd

In [257]:
table_data = pd.read_excel("./data_raw/DataSet_V49 (2).xlsx")

### Пустые или неинформативные даныне

In [258]:
table_data.drop(
    [
        "Bypass#",
        "Повторная оперция",
        "Тип повторной операции",
        "Плохая мобильность",
        "Открытая перация на сердце в анамнезе",
        "Ход операции",
        "Протокол коронарографии",
        "Коррекция А-В блокады",
        "Исход А-В блокады",
        "Начало А-В блокады (До/после ЧКВ)",
        "Инфаркт-зависимая артерия(Огригированная)",
        "Инфаркт-зависимая артерия(Огригированная)2",
        "Unnamed: 344",
        "SYNTAX Score",
        "ОНМК (гем) в анамнезе",
        "Калий",
        "ФЖ",
        "Пробежки ЖТ",
        "Рецидивирующая ЖТ",
        "ХСН стадия",
        "АГ",
        "Стенокардия ФК (ИБ)",
        "ЖКБ",
        "EDV",
        "Недостаточность аортального клапана (степень)",
        "Стеноз митрального клапана (степень)",
        "Недостаточность митрального клапана (степень)",
        "Недостаточность трикуспидального клапана (степень)",
        "НПВ",
        "Продолжительность операции",
        "Причина смерти",
        "PQ",
        "QRS",
        "QT",
        "RR",
        "Моноциты (абсолютное значение)(a)",
        "Эозинофилы (абсолютное значение)(a)",
        "Базофилы (абсолютное значение)(a)",
        "СОЭ(a)",
        "Эозинофилы(%)(a)",
        "Палочкоядерные нейтрофилы(%)(a)",
        "Миелоциты(%)(a)",
        "Общий белок(a)",
        "Триглицериды(a)",
        "ЛДГ(a)",
        "eGFR (a)",
        "Тропонин 1 (b)",
        "Тропонин 1 > 0.1 (b)",
        "Тропонин 1 (a)",
        "Тропонин 1 > 0.1 (a)",
        "Тропонин 1",
        "Тропонин 1 > 0.1",
        "Индекс курения",
        "Время ЧКВ",
        "А-В блокада (степень)",
        "Летальный исход икка",
        "Диагноз",
        "Дата и время развития SOFA 8 и более",
        "Часов в ОРИТ ДО развития SOFA 8",
        "Часов в ОРИТ ПОСЛЕ развития SOFA 8",
        "Максимальный прокальцитонин за сутки до развития SOFA 8",
        "Максимальный ЛАКТАТ артерия за сутки до развития SOFA 8",
        "Максимальный ЛАКТАТ вена за сутки до развития SOFA 8",
        "Максимальный ЛАКТАТ артерия за сутки после развития SOFA 8",
        "Максимальный ЛАКТАТ вена за сутки после развития SOFA 8",
        "SOFA первый раз больше или равна 8 баллам",
        "SOFA до развития 8 и более баллов",
        "Используемый антибиотик ДО развития SOFA 8 и более",
        "Левофлоксацин антибиотик ДО развития SOFA 8 и более",
        "Линезолид антибиотик ДО развития SOFA 8 и более",
        "Меропенем антибиотик ДО развития SOFA 8 и более",
        "Метронидазол антибиотик ДО развития SOFA 8 и более",
        "Моксифлоксацин антибиотик ДО развития SOFA 8 и более",
        "Нифуроксазид антибиотик ДО развития SOFA 8 и более",
        "Фосфомицин антибиотик ДО развития SOFA 8 и более",
        "Цефазолин антибиотик ДО развития SOFA 8 и более",
        "Сульбактам антибиотик ДО развития SOFA 8 и более",
        "Цефоперазон антибиотик ДО развития SOFA 8 и более",
        "Цефтриаксон антибиотик ДО развития SOFA 8 и более",
        "Количество часов применения антибиотика ДО развития SOFA 8 и более",
        "Антибиотик после развития SOFA 8 и более",
        "Моксифлоксацин после развития SOFA 8 и более",
        "Левофлоксацин после развития SOFA 8 и более",
        "Азитромицин после развития SOFA 8 и более",
        "Линезолид после развития SOFA 8 и более",
        "Меропенем после развития SOFA 8 и более",
        "Метронидазол после развития SOFA 8 и более",
        "Нифуроксазид после развития SOFA 8 и более",
        "Фосфомицин после развития SOFA 8 и более",
        "Цефазолин после развития SOFA 8 и более",
        "Сульбактам после развития SOFA 8 и более",
        "Цефепим после развития SOFA 8 и более",
        "Цефтриаксон после развития SOFA 8 и более",
        "Через сколько часов после развития SOFA 8 и более был введен антибиотик",
        "APACHE сутки до развития SOFA 8 и более",
        "APACHE сутки ПОСЛЕ развития SOFA 8 и более",
        "АД среднее за сутки до развития SOFA 8",
    ],
    axis=1,
    inplace=True,
)

### Обработка типов данных колонок

В ходе работы с данными выяснилось, что есть дубликаты - повторные записи пациентов в зависимости от повторных госпитализаций

Для решаемой задачи классификации это не является проблемой, так как каждая отдельная госпитализация рассматривается как отдельный случай и мы смотрим на риски неблагоприятного исхода в тот или иной момент госпитализации. 

Но, если мы начинаем разбивать нашу выборку на обучающую, тестовую и валидационную, то возникнет проблема - модель увидит одного и того же пациента в разных выборках и переобучится. Это решается с помощью стратифицированного разбиения пациентов по id (GroupKFold или train_test_split с группировкой на пациента)

In [259]:
table_data.head(3)

,Код пациента,Name,Age,Sex,Наличие в БД,Наличие в файле,STEMI,ЧКВ,Дата STEMI,Вид STEMI,...,BEVenMax,HCO3VenMin (b),HCO3VenMin (a),HCO3VenMin,HCO3VenMax (b),HCO3VenMax (a),HCO3VenMax,BNP (b),BNP (a),BNP
0,20-6545,Хасьянов РА,78.0,М,Да,Да,Нет,Да,NaN,NaN,...,-5.0,18.5,18.5,18.5,18.5,18.5,18.5,NaN,NaN,NaN
1,19-22109,Тюркова ГГ,80.0,Ж,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17-13439,Ремизов РВ,40.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
counts = table_data["Name"].value_counts()
duplicated_names = counts[counts > 1].index.to_list()
duplicated_df = table_data[table_data["Name"].isin(duplicated_names)]

duplicated_df

,Код пациента,Name,Age,Sex,Наличие в БД,Наличие в файле,STEMI,ЧКВ,Дата STEMI,Вид STEMI,...,BEVenMax,HCO3VenMin (b),HCO3VenMin (a),HCO3VenMin,HCO3VenMax (b),HCO3VenMax (a),HCO3VenMax,BNP (b),BNP (a),BNP
0,20-6545,Хасьянов РА,78.0,М,Да,Да,Нет,Да,NaN,NaN,...,-5.0,18.5,18.5,18.5,18.5,18.5,18.5,NaN,NaN,NaN
11,975,Щетинкин ЮВ,56.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,590,Вирич ВИ,75.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,1722,Бабич АП,65.0,Ж,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,17-12105,Бабаев СН,59.0,NaN,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17419,10407,Ефименко ВИ,64.0,М,Да,Да,Да,Да,2015-07-16 00:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17425,10019,Гаевский АИ,60.0,М,Да,Да,Да,Да,2021-06-08 00:00:00,Передний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17427,1,Халиман ОА,48.0,М,Да,Да,Да,Да,2020-01-01 00:00:00,Передний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17428,2024-06-18 00:00:00,Журавлев АЮ,50.0,М,Да,Да,Да,Да,2018-01-01 00:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17429,2024-04-19 00:00:00,Петров ВЮ,53.0,М,Да,Да,Да,Да,2018-12-31 00:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Всего записей-дубликатов - около 5к. 

Почти все из них - это повторные госпитализации. Вероятно, среди них есть и полные дубликаты записей, и некорректные строки. 
Все такие записи имеют уникальный код пациента

## Обработка данных

В ходе анализа датасета были выявлены МНОГОЧИСЛЕННЫЕ ошибки в формировании и заполнении датасета. По возможности, эти проблемы требуется исправить вручную

Обработка пропусков в колонке Пол. Данные заполнялись по сколнениям фамилии только там, где была уверенность в принадлежности к тому или иному полу. "Пограничные" случаи оставались None

### Расчет индекса массы тела

In [285]:
table_data[["Индекс массы тела", "Рост", "Вес"]].head(3)

     Индекс массы тела   Рост   Вес
47                 NaN    NaN  79.0
106                NaN  172.0  80.0
158                NaN    NaN  69.0

In [ ]:
mask = table_data["Рост"].notna() & table_data["Вес"].notna()
table_data.loc[mask, "Индекс массы тела"] = table_data.loc[mask, "Вес"] / (table_data.loc[mask, "Рост"] / 100) ** 2

In [286]:
table_data[["Индекс массы тела", "Рост", "Вес"]].head(3)

     Индекс массы тела   Рост   Вес
47                 NaN    NaN  79.0
106                NaN  172.0  80.0
158                NaN    NaN  69.0

In [ ]:
# Loaded variable 'table_data' from kernel state

# Sort by column: 'Sex' (ascending)
table_data = table_data.sort_values(["Sex"], na_position="first")

table_data.loc[47, "Sex"] = "М"
table_data.loc[106, "Sex"] = "М"
table_data.loc[158, "Sex"] = "М"
table_data.loc[568, "Sex"] = "М"
table_data.loc[882, "Sex"] = "М"
table_data.loc[1064, "Sex"] = "М"
table_data.loc[1197, "Sex"] = "М"
table_data.loc[1241, "Sex"] = "М"
table_data.loc[1513, "Sex"] = "М"
table_data.loc[1871, "Sex"] = "М"
table_data.loc[2420, "Sex"] = "М"
table_data.loc[2423, "Sex"] = "М"
table_data.loc[3133, "Sex"] = "Ж"
table_data.loc[3406, "Sex"] = "М"
table_data.loc[4306, "Sex"] = "Ж"
table_data.loc[5320, "Sex"] = "М"
table_data.loc[6157, "Sex"] = "Ж"
table_data.loc[6639, "Sex"] = "Ж"
table_data.loc[6998, "Sex"] = "М"
table_data.loc[7138, "Sex"] = "М"
table_data.loc[7240, "Sex"] = "М"
table_data.loc[7468, "Sex"] = "М"
table_data.loc[7548, "Sex"] = "М"
table_data.loc[9072, "Sex"] = "М"
table_data.loc[9073, "Sex"] = "Ж"
table_data.loc[9325, "Sex"] = "М"
table_data.loc[11323, "Sex"] = "М"
table_data.loc[11330, "Sex"] = "Ж"
table_data.loc[11526, "Sex"] = "М"
table_data.loc[11703, "Sex"] = "М"
table_data.loc[11822, "Sex"] = "Ж"
table_data.loc[11831, "Sex"] = "М"
table_data.loc[11919, "Sex"] = "М"
table_data.loc[11934, "Sex"] = "Ж"
table_data.loc[12078, "Sex"] = "М"
table_data.loc[12182, "Sex"] = "М"
table_data.loc[11216, "Sex"] = "М"
table_data.loc[11272, "Sex"] = "М"
table_data.loc[12471, "Sex"] = "М"
table_data.loc[12552, "Sex"] = "Ж"
table_data.loc[15950, "Sex"] = "М"

In [49]:
table_data["Стентирование в анамнезе"].value_counts()

Стентирование в анамнезе
0      3337
1      1360
Нет      63
Да        4
Name: count, dtype: int64

In [ ]:
mapping = {"да": 1, "нет": 0, "1": 1, "0": 0}

table_data["Стентирование в анамнезе"] = table_data["Стентирование в анамнезе"].replace(mapping)

### TODO: Разбить разные варианты на разные колонки и привести к единому виду

In [51]:
table_data["Форма ФП"].value_counts()

Форма ФП
Пароксизм ФП                             1002
Постоянная форма ФП                       713
Пароксизмальная форма ФП Пароксизм ФП     379
Пароксизмальная форма ФП                  364
Персистирующая форма ФП                    43
                                         ...
Пароксизмальная форма фп Пароксизм фп       1
Постоянная форма                            1
Пароксизм фП                                1
ПароксизмФП                                 1
Пароксизмальная форма ФП Пароксзим ФП       1
Name: count, Length: 63, dtype: int64

In [262]:
mapping = {
    "ПароксизмФП": "Пароксизм ФП",
    "Пароксизм фп": "Пароксизм ФП",
    "Пароксизмальная форма фп": "Пароксизмальная форма ФП",
}

table_data["Форма ФП"] = table_data["Форма ФП"].replace(mapping)

-------------

In [53]:
table_data["Дилатация предсердий"].value_counts()

Дилатация предсердий
Нет                  687
дилатация ЛП, ПП     431
дилатация ЛП         391
нет данных            47
дилатация лп           8
дилатация ЛП,ПП        7
дилатация ПП           5
дилатация ЛП, ПП       1
увеличение ЛП          1
дилатация лп, пп       1
дилятация ЛП           1
Name: count, dtype: int64

In [263]:
mapping = {
    "нет данных": "Нет",
    "дилатация лп": "дилатация ЛП",
    "дилятация ЛП": "дилатация ЛП",
    "дилатация ЛП, ПП ": "дилатация ЛП,ПП",
    "дилатация ЛП, ПП": "дилатация ЛП,ПП",
    "дилатация лп, пп": "дилатация ЛП,ПП",
    "увеличение ЛП": "дилатация ЛП",
}

table_data["Дилатация предсердий"] = table_data["Дилатация предсердий"].replace(mapping)

In [55]:
table_data["Дилатация предсердий"].value_counts()

Дилатация предсердий
Нет                734
дилатация ЛП,ПП    440
дилатация ЛП       401
дилатация ПП         5
Name: count, dtype: int64

---------------

In [56]:
table_data["ФП b (после чкв)"].value_counts()

ФП b (после чкв)
Нет     12457
Да       2710
ЛОЖЬ        2
Name: count, dtype: int64

In [264]:
mapping = {"ЛОЖЬ": "Нет"}

table_data["ФП b (после чкв)"] = table_data["ФП b (после чкв)"].replace(mapping)

In [58]:
table_data["ФП b (после чкв)"].value_counts()

ФП b (после чкв)
Нет    12459
Да      2710
Name: count, dtype: int64

-------------

In [59]:
table_data["MKB"].value_counts()

MKB
I20.0    2376
I21.1    1992
I21.0    1891
I21.9    1854
I21.4     828
         ...
M34.0       1
K62.1       1
J15.8       1
M54.1       1
N11.0       1
Name: count, Length: 464, dtype: int64

In [265]:
table_data["MKB"] = table_data["MKB"].astype(str).str.strip().str.upper()

In [266]:
mapping = {
    "I20.00": "I20.0",
    "I20.80": "I21.0",
    "I21.10": "I21.1",
    "I21.40": "I21.4",
    "I21.90": "I21.9",
    "I22.00": "I22.0",
    "I22.10": "I22.1",
    "I22.80": "I22.8",
    "I22.90": "I22.9",
    "I25.50": "I25.5",
    "I60.60": "I60.6",
    "I61.00": "I61.0",
    "I61.40": "I61.4",
    "I63.30": "I63.3",
    "I63.40": "I63.4",
    "I67.20": "I67.2",
    "I69.80": "I69.8",
    "None": "NaN",
    "2022-09-21 00:00:00": "NaN",
}

table_data["MKB"] = table_data["MKB"].replace(mapping)

------------

In [65]:
table_data["ХСН фк"].value_counts()

ХСН фк
2        7992
IIFK     2553
0        1436
1         972
3         910
IIIFK     167
IFK       150
4          51
IVFK        4
Name: count, dtype: int64

----------

In [69]:
table_data["Вид операции(ИБ)(Новый)"].value_counts()

Вид операции(ИБ)(Новый)
ТЛБАП                                                                                                             10215
ЧКА                                                                                                                2075
чка                                                                                                                1942
-                                                                                                                   974
Реканализация                                                                                                        50
Аорто-коронарное шунтирование                                                                                         9
ТЛБАП со стентированием ПМЖВ                                                                                          7
Протезирование                                                                                                        4
Тромбаспирация                                                                                                        4
Реваскуляризация миокарда                                                                                             4
Пункция перикарда                                                                                                     2
ТЛБАП со стентированием ПКА.                                                                                          2
ТЛБАП со стентированием ПКА                                                                                           2
реваскуляризация миокарда                                                                                             2
ТЛБАП со стентированием ПМЖВ.                                                                                         2
Аорто-коронарное шунтирование.                                                                                        2
Чка                                                                                                                   2
ТЛБАП со стентированием ПМЖВ (ХТО).                                                                                   1
ТЛБАП со стентированием ствола ЛКА с выходом в ОВ                                                                     1
ЭИТ                                                                                                                   1
ТЛБАП со стентированием ПМЖВ, ОВ с выходом в ствол ЛКА                                                                1
ТЛБАП со стентированием ПМЖВ, ОВ                                                                                      1
ТЛБАП со стентированием ОВи ПМЖВ                                                                                      1
ТЛБАП со стентированиемОВ-ВТК                                                                                         1
ТЛБАП и стентирование ПМЖВ                                                                                            1
ТЛБАП со стентированием ОВ                                                                                            1
ТЛБАП со стентированием ОВ, ПМЖВ                                                                                      1
Имплантация ЭКС 460 в режиме DDDR                                                                                     1
ТЛБАП со стентированием ОВ и ПКА.                                                                                     1
Аспирация тромботических масс                                                                                         1
?Имплантация ЭКС 460??                                                                                                1
ТЛБАП со стентированием ПМЖВ с выходом в ствол ЛКА                                                                    1
ТЛБАП со стентированием стволаЛКА и ПМЖВ                                                                              1
ТЛБАП ПМЖВ.                                                                                                           1
Остановка? кровотечения из периферического сосуда? эндоскопическая? с использованием электрокоагуляции.               1
имплантация ЭКС 460 DR?                                                                                               1
Бедренно-подколенное шунтирование справа ниже щели коленного сустава в сочетании с ТЛБАП артерий правой голени        1
?Имплантация ЭКС 460                                                                                                  1
Лапароскопическая аппендектомия                                                                                       1
ТЛБАП со стентированием ПКА, ВТК1                                                                                     1
ТЛБАП со стентированиемПМЖВ                                                                                           1
Гемиляминэктомия                                                                                                      1
Эндартерэктомия                                                                                                       1
Реваскуляризация                                                                                                      1
Имплантация                                                                                                           1
Name: count, dtype: int64

### Все категории, их количество и целесобразность использования - сомнительны

In [270]:
mapping = {
    "чка": "ЧКА",
    "ТЛБАП со стентированием ПМЖВ.": "ТЛБАП со стентированием ПМЖВ",
    "реваскуляризация миокарда": "Реваскуляризация миокарда",
    "Чка": "ЧКА",
    "ТЛБАП со стентированием ПКА.": "ТЛБАП со стентированием ПКА",
    "ТЛБАП и стентирование ПМЖВ": "ТЛБАП со стентированием ПМЖВ",
    "ТЛБАП со стентированиемПМЖВ": "ТЛБАП со стентированием ПМЖВ",
    "Реваскуляризация": "Реваскуляризация миокарда",
    "?Имплантация ЭКС 460??": "-",
    "ТЛБАП ПМЖВ.": "ТЛБАП со стентированием ПМЖВ",
}

table_data["Вид операции(ИБ)(Новый)"] = table_data["Вид операции(ИБ)(Новый)"].replace(mapping)

In [220]:
table_data["Вид операции(ИБ)(Новый)"].value_counts()

Вид операции(ИБ)(Новый)
ТЛБАП                                                                                                             10215
ЧКА                                                                                                                4019
-                                                                                                                   975
Реканализация                                                                                                        50
ТЛБАП со стентированием ПМЖВ                                                                                         12
Аорто-коронарное шунтирование                                                                                         9
Реваскуляризация миокарда                                                                                             7
ТЛБАП со стентированием ПКА                                                                                           4
Протезирование                                                                                                        4
Тромбаспирация                                                                                                        4
Пункция перикарда                                                                                                     2
Аорто-коронарное шунтирование.                                                                                        2
ТЛБАП со стентированием ПМЖВ (ХТО).                                                                                   1
ЭИТ                                                                                                                   1
ТЛБАП со стентированием ствола ЛКА с выходом в ОВ                                                                     1
ТЛБАП со стентированием ОВ, ПМЖВ                                                                                      1
ТЛБАП со стентированием ОВ и ПКА.                                                                                     1
Имплантация ЭКС 460 в режиме DDDR                                                                                     1
ТЛБАП со стентированием ПМЖВ, ОВ с выходом в ствол ЛКА                                                                1
ТЛБАП со стентированием ПМЖВ, ОВ                                                                                      1
ТЛБАП со стентированием ОВи ПМЖВ                                                                                      1
ТЛБАП со стентированием ОВ                                                                                            1
ТЛБАП со стентированиемОВ-ВТК                                                                                         1
ТЛБАП со стентированием ПМЖВ с выходом в ствол ЛКА                                                                    1
Аспирация тромботических масс                                                                                         1
ТЛБАП со стентированием стволаЛКА и ПМЖВ                                                                              1
Остановка? кровотечения из периферического сосуда? эндоскопическая? с использованием электрокоагуляции.               1
имплантация ЭКС 460 DR?                                                                                               1
Бедренно-подколенное шунтирование справа ниже щели коленного сустава в сочетании с ТЛБАП артерий правой голени        1
?Имплантация ЭКС 460                                                                                                  1
Лапароскопическая аппендектомия                                                                                       1
ТЛБАП со стентированием ПКА, ВТК1                                                                                     1
Гемиляминэктомия                                                                                                      1
Эндартерэктомия                                                                                                       1
Имплантация                                                                                                           1
Name: count, dtype: int64

------------------

In [72]:
table_data["ДАД(a)"].value_counts()

ДАД(a)
80     2698
70     2467
80     1960
70     1608
90      642
       ...
30        1
701       1
105       1
46        1
94        1
Name: count, Length: 135, dtype: int64

In [ ]:
mapping = {r"\80": 80, r"\70": 70}

table_data["ДАД(a)"] = table_data["ДАД(a)"].replace(mapping)

In [74]:
table_data["ДАД(a)"].value_counts()

ДАД(a)
80     2698
70     2467
80     1962
70     1609
90      642
       ...
30        1
701       1
105       1
46        1
94        1
Name: count, Length: 133, dtype: int64

---------------

In [77]:
table_data["CADILLAC (Низкий риск)"].value_counts()

CADILLAC (Низкий риск)
0      2951
Нет    2676
1      2444
Да     1514
Name: count, dtype: int64

In [ ]:
mapping = {"Нет": 0, "Да": 1}

table_data["CADILLAC (Низкий риск)"] = table_data["CADILLAC (Низкий риск)"].replace(mapping)
table_data["CADILLAC (Средний риск)"] = table_data["CADILLAC (Средний риск)"].replace(mapping)
table_data["CADILLAC (Высокий риск)"] = table_data["CADILLAC (Высокий риск)"].replace(mapping)
table_data["РЕКОРД (Низкий риск)"] = table_data["РЕКОРД (Низкий риск)"].replace(mapping)
table_data["РЕКОРД (Средний риск)"] = table_data["РЕКОРД (Средний риск)"].replace(mapping)
table_data["РЕКОРД (Высокий риск)"] = table_data["РЕКОРД (Высокий риск)"].replace(mapping)

In [79]:
table_data["CADILLAC (Низкий риск)"].value_counts()

CADILLAC (Низкий риск)
0.0    5627
1.0    3958
Name: count, dtype: int64

In [80]:
table_data["РЕКОРД (Высокий риск)"].value_counts()

РЕКОРД (Высокий риск)
1.0    10041
0.0     4621
Name: count, dtype: int64

In [81]:
table_data

,Код пациента,Name,Age,Sex,Наличие в БД,Наличие в файле,STEMI,ЧКВ,Дата STEMI,Вид STEMI,...,BEVenMax,HCO3VenMin (b),HCO3VenMin (a),HCO3VenMin,HCO3VenMax (b),HCO3VenMax (a),HCO3VenMax,BNP (b),BNP (a),BNP
47,17-12105,Бабаев СН,59.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,17-17180,Ползиков СВ,58.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,15536,Анфёров ЮА,74.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461,21-8249,Арутюнян МА,66.0,NaN,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
568,17-20825,Кондрашин АА,31.0,М,Нет,Да,Нет,Нет,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6503,19-9921,Шишов ГД,71.0,М,Да,Да,Да,Да,2019-06-12 00:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6505,19-9912,Рой АГ,63.0,М,Да,Да,Да,Да,2019-06-11 00:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6506,19-99,Красулин НТ,64.0,М,Да,Да,Да,Да,2019-01-05 00:00:00,Передний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6485,19-1267,Сасов КП,70.0,М,Да,Да,Нет,Да,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17429,2024-04-19 00:00:00,Петров ВЮ,53.0,М,Да,Да,Да,Да,2018-12-31 00:00:00,Задний,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Потенциальные data leak, техническая информация или шум в данных

In [273]:
questionable_columns = [
    "Наличие в БД",
    "Наличие в файле",
    "Дата STEMI",
    "ФП b (после чкв)",
    "Дата направления (Общий анализ крови)",
    "Дата взятия биоматериала (Общий анализ крови)",
    "Дата выполнения (Общий анализ крови)",
    "Дата направления (Общий анализ крови-экспрес)",
    "Дата взятия биоматериала (Общий анализ крови-экспрес)",
    "Дата выполнения (Общий анализ крови-экспрес)",
    "Начало операции(ИБ)(Новый)",
    "Конец операции(ИБ)(Новый)",
    "Продолжительность операции",
    "Экстренная операция(ИБ)(Новый)",
    "Вид операции(ИБ)(Новый)",
    "дата поступления",
    "дата выписки",
    "длительность нахождения в стационаре",
    "Исход заболевания",
    "дата смерти",
    "повторные операции",
    "Повторная оперция",
    "Тип первой операции БД",
    "Тип повторной операции",
    "Поступление в реанимацию",
    "Выписка из реанимации",
    "Количество дней в реанимации",
    "Смерть в реанимации",
    "Apache II",  # Подумать, обсудить
    "Причина смерти",
    "Срочность",
    "Лейкоциты(a)",
    "Нейтрофилы (абсолютное значение)(a)",
    "Лимфоциты (абсолютное значение)(a)",
    "Моноциты (абсолютное значение)(a)",
    "Эозинофилы (абсолютное значение)(a)",
    "Базофилы (абсолютное значение)(a)",
    "Эр(a)",
    "Hb(a)",
    "Гематокрит(a)",
    "Тромбоциты(a)",
    "СОЭ(a)",
    "Эозинофилы(%)(a)",
    "Палочкоядерные нейтрофилы(%)(a)",
    "Cегментоядерные нейтрофилы(%)(a)",
    "Лимфоциты(%)(a)",
    "Моноциты(%)(a)",
    "Миелоциты(%)(a)",
    "Общий белок(a)",
    "Глюкоза(a)",
    "АСАТ(a)",
    "АЛАТ(a)",
    "Билирубин общий(a)",
    "Холестерин общий(a)",
    "Триглицериды(a)",
    "Креатинин(a)",
    "Мочевина(a)",
    "ЛДГ(a)",
    "КФК(a)",
    "КФК-МВ(a)",
    "ПТИ(a)",
    "МНО(a)",
    "ФБГ(a)",
    "ТВ(a)",
    "АПТВ(a)",
    "eGFR (a)",
    "Осложнения",
    "Тропонин 1 (a)",
    "Тропонин 1 > 0.1 (a)",
    "Ход операции",
    "Протокол коронарографии",
    "Коррекция А-В блокады",
    "Исход А-В блокады",
    "Начало А-В блокады (До/после ЧКВ)",
    "Файл(Анализы)",
    "Файл(ИБ)",
    "Запись требует проверки",
    "Инфаркт-зависимая артерия(Огригированная)",
    "Инфаркт-зависимая артерия(Огригированная)2",
    "Ишемический инсульт (Выгрузка из ИБ - временный столбец)",
    "Геморрагический инсульт (Выгрузка из ИБ - временный столбец)",
    "Инсульт (Выгрузка из ИБ - временный столбец)",
    "Отек легких(a)",
    "Время ЧКВ",
    "Летальный исход икка",
    "Дата и время развития SOFA 8 и более",
    "Время введения первого антибиотика",
    "Часов до введения первого антибиотика",
    "Часов в ОРИТ ДО развития SOFA 8",
    "Часов в ОРИТ ПОСЛЕ развития SOFA 8",
    "Максимальный прокальцитонин за сутки до развития SOFA 8",
    "Максимальный ЛАКТАТ артерия за сутки до развития SOFA 8",
    "Максимальный ЛАКТАТ вена за сутки до развития SOFA 8",
    "Максимальный ЛАКТАТ артерия за сутки после развития SOFA 8",
    "Максимальный ЛАКТАТ вена за сутки после развития SOFA 8",
    "SOFA первый раз больше или равна 8 баллам",
    "SOFA до развития 8 и более баллов",
    "Используемый антибиотик ДО развития SOFA 8 и более",
    "Левофлоксацин антибиотик ДО развития SOFA 8 и более",
    "Линезолид антибиотик ДО развития SOFA 8 и более",
    "Меропенем антибиотик ДО развития SOFA 8 и более",
    "Метронидазол антибиотик ДО развития SOFA 8 и более",
    "Моксифлоксацин антибиотик ДО развития SOFA 8 и более",
    "Нифуроксазид антибиотик ДО развития SOFA 8 и более",
    "Фосфомицин антибиотик ДО развития SOFA 8 и более",
    "Цефазолин антибиотик ДО развития SOFA 8 и более",
    "Сульбактам антибиотик ДО развития SOFA 8 и более",
    "Цефоперазон антибиотик ДО развития SOFA 8 и более",
    "Цефтриаксон антибиотик ДО развития SOFA 8 и более",
    "Количество часов применения антибиотика ДО развития SOFA 8 и более",
    "Антибиотик после развития SOFA 8 и более",
    "Моксифлоксацин после развития SOFA 8 и более",
    "Левофлоксацин после развития SOFA 8 и более",
    "Азитромицин после развития SOFA 8 и более",
    "Линезолид после развития SOFA 8 и более",
    "Меропенем после развития SOFA 8 и более",
    "Метронидазол после развития SOFA 8 и более",
    "Нифуроксазид после развития SOFA 8 и более",
    "Фосфомицин после развития SOFA 8 и более",
    "Цефазолин после развития SOFA 8 и более",
    "Сульбактам после развития SOFA 8 и более",
    "Цефепим после развития SOFA 8 и более",
    "Цефтриаксон после развития SOFA 8 и более",
    "Через сколько часов после развития SOFA 8 и более был введен антибиотик",
    "APACHE сутки до развития SOFA 8 и более",
    "APACHE сутки ПОСЛЕ развития SOFA 8 и более",
    "АД среднее за сутки до развития SOFA 8",
    "Среднее АД 1 сутки в орит",
    "Минимальное АД 1 сут",
    "Макс АД 1 сут",
    "Среднее АД 3 сутки в орит",
    "Минимальное АД 3 сут",
    "Макс АД 3 сут",
    "Среднее АД 7 сутки в орит",
    "Минимальное АД 7 сут",
    "Макс АД 7 сут",
    "Среднее ЧСС 1 сутки",
    "Мин ЧСС 1 сутки",
    "Максимальное ЧСС 1 сутки",
    "Среднее ЧСС 3 сутки",
    "Мин ЧСС 3 сутки",
    "Максимальное ЧСС 3 сутки",
    "Среднее ЧСС 7 сутки",
    "Мин ЧСС 7 сутки",
    "Максимальное ЧСС 7 сутки",
    "Лейкоциты больше 9 до назначения аб",
    "ИВЛ",
    "Вазопрессорная поддержка",
    "Набор данных (Данные Кокарев)",
    "Unnamed: 344",
    "Адреналин",
    "Добутамин",
    "Допмин",
    "Норадреналин",
    "Левосимендан",
    "Мезатон",
    "Max Aдреналин",
    "Max Добутамин",
    "Max Допмин",
    "Max Норадреналин",
    "Max Мезатона",
    "В базе данных",
    "Натрий (Na) (a)",
    "Калий (K) (a)",
    "Хлор (Cl) (a)",
    "Кальций ионизированный (Ca+) (a)",
    "pHARTmin (a)",
    "pHARTmax (a)",
    "pO2ARTmin (a)",
    "pO2ARTmax (a)",
    "pCO2min (a)",
    "pCO2max (a)",
    "SaO2min (a)",
    "SaO2max (a)",
    "LACTartMin (a)",
    "LACTartMax (a)",
    "BEArtMin (a)",
    "BEArtMax (a)",
    "HCO3ArtMin (a)",
    "HCO3ArtMax (a)",
    "PHVenMin (a)",
    "PHVenMax (a)",
    "PO2VenMin (a)",
    "PO2VenMax (a)",
    "PCO2VenMin (a)",
    "PCO2VenMax (a)",
    "ScvO2Min (a)",
    "ScvO2Max (a)",
    "LactVenMin (a)",
    "LactVenMax (a)",
    "BEVenMin (a)",
    "BEVenMax (a)",
    "HCO3VenMin (a)",
    "HCO3VenMax (a)",
    "BNP (a)",
]

In [274]:
test_table = table_data.drop(questionable_columns, axis=1, errors="ignore")

### Колокни для которых потребуется дополнительная предобработка

- Распределение эритроцитов по объему (RDW-SD)
- Тромбокрит
- Коэффициент крупных тромбоцитов

### В датасете присутствует большое количество колонок, которые имеют абсолютные и относительные значения, что может искажать картину для модели

Помимо этого, на этом этапе мы отчищаем другие неиспользуемые или ненужные нам колонки

UPD: Если колонка имеет (а), (b), то мы берем запись без нее (среднее между a и b)

In [ ]:
questionable_columns = [
    "ФВ ЛЖ",
    "Нейтрофилы (относительное значение)",
    "Лимфоциты (относительное значение)",
    "Моноциты (относительное значение)",
    "Эозинофилы (относительное значение)",
    "Базофилы (относительное значение)",
    "САД(a)",
    "ДАД(a)",
    "ЧСС(а)",
    "SmokeIndex",
    "pHARTmin",
    "pHARTmax",
    "pO2ARTmin",
    "pO2ARTmax",
    "pCO2min",
    "pCO2max",
    "SaO2min",
    "SaO2max",
    "LACTartMin",
    "LACTartMax",
    "BEArtMin",
    "BEArtMax",
    "HCO3ArtMin",
    "HCO3ArtMax",
    "PHVenMin",
    "PHVenMax",
    "PO2VenMin",
    "PO2VenMax",
    "PCO2VenMin",
    "PCO2VenMax",
    "ScvO2Min",
    "ScvO2Max",
    "LactVenMin",
    "LactVenMax",
    "BEVenMin",
    "BEVenMax",
    "HCO3VenMin",
    "HCO3VenMax",
    "BNP",
    "Сопутствующие1",
    "Сопутствующие2",
    "Отделение",
    "Отек легких",
    "Отек легких(b)",
    "MKB",
    "МКБ",
    "Синдромный диагноз",
    "Кардиогенный шок",
]

In [276]:
test_table = test_table.drop(columns=questionable_columns, errors="ignore")

In [111]:
test_table

,Код пациента,Name,Age,Sex,STEMI,ЧКВ,Вид STEMI,Инфаркт-зависимая артерия,Поражение ствола,Количество пораженных сосудов(Syntax),...,PCO2VenMax (b),ScvO2Min (b),ScvO2Max (b),LactVenMin (b),LactVenMax (b),BEVenMin (b),BEVenMax (b),HCO3VenMin (b),HCO3VenMax (b),BNP (b)
47,17-12105,Бабаев СН,59.0,М,Нет,Да,NaN,2,Нет,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,17-17180,Ползиков СВ,58.0,М,Нет,Да,NaN,2,Нет,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,15536,Анфёров ЮА,74.0,М,Нет,Да,NaN,ОВ - Несовадает,Нет,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461,21-8249,Арутюнян МА,66.0,NaN,Нет,Да,NaN,ПМЖВ - Несовадает,Нет,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
568,17-20825,Кондрашин АА,31.0,М,Нет,Нет,NaN,0,Нет,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6503,19-9921,Шишов ГД,71.0,М,Да,Да,Задний,ПКА,Нет,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6505,19-9912,Рой АГ,63.0,М,Да,Да,Задний,ПКА,Нет,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6506,19-99,Красулин НТ,64.0,М,Да,Да,Передний,ПМЖВ,Нет,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6485,19-1267,Сасов КП,70.0,М,Нет,Да,NaN,2,Да,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17429,2024-04-19 00:00:00,Петров ВЮ,53.0,М,Да,Да,Задний,ПКА,Нет,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Преобразование категорий в категории

In [ ]:
categories = [
    "Sex",
    "STEMI",
    "ЧКВ",
    "Вид STEMI",
    "Инфаркт-зависимая артерия",
    "Поражение ствола",
    "TIMI",
    "Инфаркт миокарда в анамнезе (<3)",
    "Инфаркт миокарда в анамнезе (>3)",
    "Инфаркт миокарда со стентированием в анамнезе",
    "ОНМК (иш) в анамнезе",
    "Стентирование в анамнезе",
    "Тромболизис",
    "Форма ФП",
    "Дилатация предсердий",
    "ФП a (в анамнезе)",
    "ФП при окс (до чкв)",
    "ФП постоянная форма",
    "Класс ОСН по Killip",
    "ХСН фк",
    "ГБ стадия",
    "ГБ риск",
    "Стенокардия (ИБ)",
    "Стенокардия форма(ИБ)",
    "СД",
    "ХБП",
    "ЯБ",
    "Стеноз аортального клапана (степень)",
    "GRACE(Общее)>140",
    "интегрилин|эптифибатид|коромакс|агграстат",
    "Экстракардиальная артериопатия",
    "Smoking",
    "Общий анализ крови раньше операции",
    "Общий анализ крови_экспресс раньше операции",
    "Аортальный стеноз (Градиент)",
    "Аортальный стеноз (Заключение)",
    "ХОБЛ (Новый столбец)",
    "А-В блокада",
    "Стенокардия в диагнозе при поступлении",
    "ПИКС в диагнозе при поступлении",
    "Курит",
    "GRACE(Общее)>156",
    "Медицинская помощь оказана за первые 4 часа",
    "Гипертоническая болезнь",
    "ФВ < 40",
    "РЕКОРД",
    "CADILLAC (Низкий риск)",
    "CADILLAC (Средний риск)",
    "CADILLAC (Высокий риск)",
    "РЕКОРД (Низкий риск)",
    "РЕКОРД (Высокий риск)",
    "GRACE (Низкий риск)",
    "GRACE (Средний риск)",
    "GRACE (Высокий риск)",
    "TIMI (Летальность) (Низкий риск)",
    "TIMI (Летальность) (Средний риск)",
    "TIMI (Летальность) (Высокий риск)",
    "PAMI (Низкий риск)",
    "PAMI (Средний риск)",
    "PAMI (Высокий риск)",
    "А-В блокаДа (Новый)",
    "UA (нестабильная стенокардия)",
    "killip",
]

### TODO: Пересмотреть логику кодирования

In [278]:
missing_label = "-1"

for col in categories:
    if col not in test_table.columns:
        continue

    test_table[col] = test_table[col].astype(str)

    # 2. Заполняем пропуски
    test_table[col] = test_table[col].fillna(missing_label)

    # 3. Приводим к типу category
    test_table[col] = test_table[col].astype("category")

print(test_table[categories].dtypes)

Sex                              category
STEMI                            category
ЧКВ                              category
Вид STEMI                        category
Инфаркт-зависимая артерия        category
                                   ...
PAMI (Средний риск)              category
PAMI (Высокий риск)              category
А-В блокаДа (Новый)              category
UA (нестабильная стенокардия)    category
killip                           category
Length: 63, dtype: object

In [182]:
test_table

,Код пациента,Name,Age,Sex,STEMI,ЧКВ,Вид STEMI,Инфаркт-зависимая артерия,Поражение ствола,Количество пораженных сосудов(Syntax),...,PCO2VenMax (b),ScvO2Min (b),ScvO2Max (b),LactVenMin (b),LactVenMax (b),BEVenMin (b),BEVenMax (b),HCO3VenMin (b),HCO3VenMax (b),BNP (b)
47,17-12105,Бабаев СН,59.0,М,Нет,Да,nan,2,Нет,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,17-17180,Ползиков СВ,58.0,М,Нет,Да,nan,2,Нет,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,15536,Анфёров ЮА,74.0,М,Нет,Да,nan,ОВ - Несовадает,Нет,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461,21-8249,Арутюнян МА,66.0,nan,Нет,Да,nan,ПМЖВ - Несовадает,Нет,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
568,17-20825,Кондрашин АА,31.0,М,Нет,Нет,nan,0,Нет,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6503,19-9921,Шишов ГД,71.0,М,Да,Да,Задний,ПКА,Нет,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6505,19-9912,Рой АГ,63.0,М,Да,Да,Задний,ПКА,Нет,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6506,19-99,Красулин НТ,64.0,М,Да,Да,Передний,ПМЖВ,Нет,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6485,19-1267,Сасов КП,70.0,М,Нет,Да,nan,2,Да,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17429,2024-04-19 00:00:00,Петров ВЮ,53.0,М,Да,Да,Задний,ПКА,Нет,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Обработка типов данных колонок

In [287]:
test_table.dtypes

Код пациента        object
Name                object
Age                float64
Sex               category
STEMI             category
                    ...
BEVenMin (b)       float64
BEVenMax (b)       float64
HCO3VenMin (b)     float64
HCO3VenMax (b)     float64
BNP (b)            float64
Length: 192, dtype: object

In [ ]:
test_table["Name"] = test_table["Name"].astype("str")
test_table["Name"] = test_table["Name"].astype("str")

In [279]:
test_table.to_csv("./data_raw/clean_table.csv")